version: "3.4"
services:
  mongo:
    build:
      context: .
      dockerfile: ./etc/docker/mongo/Dockerfile
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: collectors_choice
    ports:
      - 27017:27017
    volumes:
      - ./etc/docker/mongo/data:/data/db

  node:
    build:
      context: .
      dockerfile: ./etc/docker/node/Dockerfile
      target: dev
    container_name: node-docker
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node
    depends_on:
      - mongo
