env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 14
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "react/react-in-jsx-scope": "off",
  "sort-imports": ["error", {
    "ignoreCase": false,
    "ignoreDeclarationSort": true,
    "ignoreMemberSort": false,
    "memberSyntaxSortOrder": ["none", "all", "multiple", "single"],
    "allowSeparatedGroups": true
  }],
  "import/order": [
    1, 
    { "groups": 
      [
        "external", 
        "builtin", 
        "internal", 
        "sibling", 
        "parent", 
        "index"
      ], 
      "pathGroups": [
    { 
      "pattern": "components", 
      "group": "internal" 
    }, 
    { 
      "pattern": "common", 
      "group": "internal" 
    }, 
    { 
      "pattern": "routes/ **", 
      "group": "internal" 
    }, 
    { 
      "pattern": "assets/**", 
      "group": "internal", 
      "position": "after" 
    }
    ], 
    "pathGroupsExcludedImportTypes": 
      ["internal"], 
      "alphabetize": { 
          "order": "asc", 
          "caseInsensitive": true 
      }
    } 
  ] 
}
